// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gdnrczboejifgtkzsvnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbnJjemJvZWppZmd0a3pzdm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzY2MTMsImV4cCI6MjA3MjgxMjYxM30.AVys-1fLT6qgJislo0NhZDXud2llvdbpstSDaMAdOIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);